### ISSUE TITLE
URLs for Pre-2023 Patchnotes are faulty

### ISSUE THREAD

**Issue by RoraRaven** [FAForever/patchnotes#82]
Old patchnotes at https://patchnotes.faforever.com/pages/oldGamepatches.html

URLs contain a duplicate "/pages" which breaks the URL.

Example: Patch 3696

URL is:  https://patchnotes.faforever.com/pages/pages/game/2018/3696.html
URL should be: https://patchnotes.faforever.com/pages/game/2018/3696.html

![image](https://github.com/FAForever/patchnotes/assets/36416337/6ab23659-6e64-4e8c-8985-61f7495452d4)
![image](https://github.com/FAForever/patchnotes/assets/36416337/9baaa034-215e-4292-9527-d03e0f0bb0da)

**Comment by MrRowey** [comment]
thanks for this will look at this soon

**Comment by MrRowey** [comment]
This issuse is being closed as Pre 2023 Game Patchnotes will be moving to a new location soon.
