### ISSUE TITLE
Balance patchnotes: several sections are missing compared to their old versions

### ISSUE THREAD

**Issue by Basilisk3** [FAForever/patchnotes#87]
Missing compared to their prior versions in the old format (accessed via the Wayback Machine):
- Changes to gameplay mechanics
- Fixes which have an impact on balance
- Contributors

Example: https://patchnotes.faforever.com/pages/balance/2023/3750.html
The old version of the same site: https://web.archive.org/web/20231024163331/https://patchnotes.faforever.com/balance/3750.html#Mechanics

Balance-realted mechanic changes and fixes should be kept in the balance patchnotes. I also think that credit given to contributors should be kept in place.

**Comment by MrRowey** [comment]
the balance patchnote site is mainly meant for the simple stat changes that most people want to know about so mechanic changes are that relevant unless they change the game in a big way but can be added to one of the other categories.

Fixes are not needed as are a part of the main game patchnotes. 

the contributor section isn't needed as that is part of the main game changelog this site is just more visual to display the changes of the units.

**Comment by Basilisk3** [comment]
This is not how this should be done. First of all, if a change has a clear balance impact, it should be made available in the balance patchnotes. This has always been the case, and outright removing them, especially from older patchnotes, does not improve the patchnotes in any way. 

Secondly, game patches and balance patches used to be separate, so if you remove this information from the balance patchnotes, **you will not be able to find these changes on the website at all**. And since you do not know about the existence of a mechanic change, people will probably not look them up on GitHub either. 

You can take patch 3750 as an example, this was a balance patch, and since the mechanics-changes have been removed, you are now forced to open the GitHub just to check if there were some. Or you simply assume there were none, which would be wrong, obviously. All this accomplishes is reducing the amount of information available to the player. I do not understand the problem, if someone isn't interested in the changes to the game's mechanics, he can simply not read them, they are on the bottom of the page.

Removing the contributor section is also something that I am against, this site is being used by a lot of people and credit should be given where it is due.
